### ISSUE TITLE
Make compatible with browsers

### ISSUE THREAD

**Issue by victorb** [ipfs/js-ipfs-merkle-dag#48] opened 2016-09-21 13:35 UTC
Seems like we're dependent on `fs` to even include this module (See https://github.com/ipfs/js-ipfs-merkle-dag/blob/893aff1940a9281e31259affed05d983ca738478/src/dag-node.js#L12 ) which needs to be fixed, seems like js-ipfs-api is broken because of this as well

**Comment by dignifiedquire** [comment] 2016-09-21 13:37
This works fine, we are using `aegir` which uses `brfs` to inline `fs.readFile` calls. What errors are you actually seeing?

**Comment by daviddias** [comment] 2016-09-22 14:32
Yeah, `fs` has to be `brfs'ed`. Standard browserify/webpacking recipe :) 

How is js-ipfs-api broken though?

**Comment by victorb** [comment] 2016-09-22 14:41
@diasdavid just requiring `ipfs-api` will trigger this error in browser

**Comment by olizilla** [comment] 2016-09-25 20:18
I just hit the same issue. It'd help 3rd party projects that want to use `ipfs-api` in the browser if a browserify hint was added to the package.json

``` json
"browserify": { "transform": [ "brfs" ] }
```

**Comment by nikuda** [comment] 2016-10-03 00:55
The problem is the brfs transform will only work when the first parameter is a string, so anything like following doesn't work:

`var proto = protobuf(fs.readFileSync(path.join(__dirname, 'merkledag.proto')));`

https://github.com/substack/brfs/issues/36

**Comment by olizilla** [comment] 2016-10-04 08:49
brfs does come with some caveats, but it's smart enough for simple use-cases like inlining a local file: https://github.com/substack/brfs#methods 

I've added the brfs hint in a fork which is working. 

The trouble I hit after that is the module assumes that it'll be consumed from a release that has had `npm run build` called on it, so depending on it from a github repo wasn't so fun. The fork moves the build step to `postinstall` and pulls the build deps from devDependencies to dependencies. I have a feeling that that isn't a change that people would go for. It does however make it easier to consume the module straight from a repo, as a dev.

https://github.com/ipfs/js-ipfs-merkle-dag/compare/master...olizilla:brfs

**Comment by aakilfernandes** [comment] 2016-10-19 18:18
+1

**Comment by aakilfernandes** [comment] 2016-10-19 21:29
Just to clarify, you only need to add `"browserify": { "transform": [ "brfs" ] }` to package.json to fix this issue

**Comment by daviddias** [comment] 2016-10-26 11:48
Hi! We are getting that as part of the Async Crypto and Bundling js-ipfs + js-ipfs-api endeavours, in the meantime, this module got deprecated in favour of [ipld-dag-pb](https://github.com/ipld/js-ipld-dag-pb) and [ipld-resolver](https://github.com/ipld/js-ipld-resolver), see:

https://github.com/ipfs/js-ipfs-merkle-dag#deprecatedjs-ipfs-merkle-dag

Closing the issue :)

**Closed as completed by daviddias** 2016-10-26 11:48 UTC
Labels: kind/bug
